#!/usr/bin/env bash
# Splunk Last Known Good Configuration (LKGC) Startup Script
# Auto-generated by manage_splunk.py

echo "===> Stopping existing Splunk container (if running)..."
podman stop -t 30 splunk 2>/dev/null
podman rm splunk 2>/dev/null

echo "===> Launching Splunk Enterprise container with LKGC parameters..."
podman run -d \
  --name splunk \
  --stop-timeout 30 \
  -p 8000:8000 -p 8088:8088 -p 5514:5514/tcp -p 5515:5515/tcp -p 9997:9997/tcp -p 5515:5515/udp \
  -v splunk_data:/opt/splunk/var \
  -v splunk_etc:/opt/splunk/etc \
  -e "SPLUNK_START_ARGS=--accept-license" \
  -e "SPLUNK_GENERAL_TERMS=--accept-sgt-current-at-splunk-com" \
  -e "SPLUNK_PASSWORD=YourSecurePassword123!" \
  -e "SPLUNK_LICENSE_URI=Free" \
  docker.io/splunk/splunk:latest

echo "===> Splunk container 'splunk' started successfully!"
